# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\nusers.grpc\"\x07\n\x05\x45mpty\"\x1d\n\x0fUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"Q\n\x10UserByIdResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"I\n\x08UserData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"4\n\rUsersResponse\x12#\n\x05users\x18\x01 \x03(\x0b\x32\x14.users.grpc.UserData\"@\n\x13RegisterUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"\"\n\x14RegisterUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x12\x44\x65leteUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\">\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"$\n\x12UpdateUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xfd\x02\n\x0cUsersService\x12\x38\n\x08GetUsers\x12\x11.users.grpc.Empty\x1a\x19.users.grpc.UsersResponse\x12H\n\x0bGetUserById\x12\x1b.users.grpc.UserByIdRequest\x1a\x1c.users.grpc.UserByIdResponse\x12O\n\nCreateUser\x12\x1f.users.grpc.RegisterUserRequest\x1a .users.grpc.RegisterUserResponse\x12K\n\nUpdateUser\x12\x1d.users.grpc.UpdateUserRequest\x1a\x1e.users.grpc.UpdateUserResponse\x12K\n\nDeleteUser\x12\x1d.users.grpc.DeleteUserRequest\x1a\x1e.users.grpc.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=27
  _globals['_EMPTY']._serialized_end=34
  _globals['_USERBYIDREQUEST']._serialized_start=36
  _globals['_USERBYIDREQUEST']._serialized_end=65
  _globals['_USERBYIDRESPONSE']._serialized_start=67
  _globals['_USERBYIDRESPONSE']._serialized_end=148
  _globals['_USERDATA']._serialized_start=150
  _globals['_USERDATA']._serialized_end=223
  _globals['_USERSRESPONSE']._serialized_start=225
  _globals['_USERSRESPONSE']._serialized_end=277
  _globals['_REGISTERUSERREQUEST']._serialized_start=279
  _globals['_REGISTERUSERREQUEST']._serialized_end=343
  _globals['_REGISTERUSERRESPONSE']._serialized_start=345
  _globals['_REGISTERUSERRESPONSE']._serialized_end=379
  _globals['_DELETEUSERREQUEST']._serialized_start=381
  _globals['_DELETEUSERREQUEST']._serialized_end=412
  _globals['_DELETEUSERRESPONSE']._serialized_start=414
  _globals['_DELETEUSERRESPONSE']._serialized_end=450
  _globals['_UPDATEUSERREQUEST']._serialized_start=452
  _globals['_UPDATEUSERREQUEST']._serialized_end=514
  _globals['_UPDATEUSERRESPONSE']._serialized_start=516
  _globals['_UPDATEUSERRESPONSE']._serialized_end=552
  _globals['_USERSSERVICE']._serialized_start=555
  _globals['_USERSSERVICE']._serialized_end=936
# @@protoc_insertion_point(module_scope)
